import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'jp';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.programs': 'Programs',
    'nav.whyUs': 'Why Us',
    'nav.partners': 'Partners',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contact',
    'nav.freeConsultation': 'Free Consultation',

    // Hero Section
    'hero.label': 'HANAMICHI GLOBAL EDUCATION',
    'hero.title1': 'Find the Perfect Place',
    'hero.title2': 'to Make Your Dreams',
    'hero.title3': 'Come True.',
    'hero.description': 'Career planning is an adventure that excites your future. One more step today — until you meet the wonderful you.',
    'hero.cta1': 'Free Consultation',
    'hero.cta2': 'Explore Programs',
    'hero_2.label': 'INTERNATIONAL OPPORTUNITIES',
    'hero_2.title1': 'Unlock Your',
    'hero_2.title2': 'Global Potential',
    'hero_2.title3': 'Today.',
    'hero_2.description': 'Access world-class universities and life-changing study tours designed to broaden horizons and build international careers.',
    'hero_3.label': 'EXPERT GUIDANCE',
    'hero_3.title1': 'Your Journey',
    'hero_3.title2': 'To Success',
    'hero_3.title3': 'Starts Here.',
    'hero_3.description': 'Step-by-step guidance for students at every level to discover hidden pathways and international experiences that transform futures.',

    // Home Page Sections
    'home.recruiting.label': 'NOW RECRUITING',
    'home.recruiting.title': 'Programs Now Accepting Applications',
    'home.recruiting.viewAll': 'View All Programs',
    'home.invisible.label': 'SEE THE INVISIBLE',
    'home.invisible.title1': 'Some Opportunities',
    'home.invisible.title2': 'Cannot Be Seen',
    'home.invisible.title3': 'Until Someone Shows You',
    'home.invisible.description': 'We help you discover paths that others might miss, guiding you towards a future that truly matches your potential.',
    'home.trackRecord.label': 'OUR TRACK RECORD',
    'home.trackRecord.title': 'Global Reach, Local Impact',
    'home.trackRecord.description': 'We have successfully guided students to prestigious institutions and life-changing experiences across the globe.',
    'home.whyHanamichi.title': 'Why Choose HANAMICHI?',
    'home.whyHanamichi.feature1.title': 'Personalized Path',
    'home.whyHanamichi.feature1.desc': 'We focus on your unique strengths and goals to find the perfect international fit.',
    'home.whyHanamichi.feature2.title': 'Expert Counseling',
    'home.whyHanamichi.feature2.desc': 'Our experienced mentors provide end-to-end support for your global journey.',
    'home.whyHanamichi.feature3.title': 'Global Network',
    'home.whyHanamichi.feature3.desc': 'Access exclusive partnerships with top universities and institutions worldwide.',
    'home.whyHanamichi.feature4.title': 'Proven Success',
    'home.whyHanamichi.feature4.desc': 'Join hundreds of students who have transformed their lives through our programs.',
    'home.whyHanamichi.feature5.title': 'Community Support',
    'home.whyHanamichi.feature5.desc': 'Become part of a thriving network of global-minded individuals.',
    'home.journey.title': 'Your Journey With HANAMICHI',
    'home.journey.step1.title': 'Free Consultation',
    'home.journey.step1.desc': 'Understanding student goals and interests.',
    'home.journey.step2.title': 'Program Planning',
    'home.journey.step2.desc': 'Choosing countries and educational institutions.',
    'home.journey.step3.title': 'Preparation',
    'home.journey.step3.desc': 'Language training and cultural orientation.',
    'home.journey.step4.title': 'Application',
    'home.journey.step4.desc': 'Handling admissions and documentation.',
    'home.journey.step5.title': 'Departure',
    'home.journey.step5.desc': 'Final briefing and travel arrangements.',
    'home.journey.step6.title': 'On-site Support',
    'home.journey.step6.desc': 'Continuous guidance during your stay.',
    'home.partners.label': 'OUR PARTNERS',
    'home.partners.title': 'Global Collaborations',
    'home.partners.subtitle': 'International Institutions',
    'home.partners.viewAll': 'View All Partners',
    'home.partners.domestic.label': 'DOMESTIC BASE',
    'home.partners.domestic.title': 'HANAMICHI LLC — Japan Office',
    'home.partners.domestic.desc': 'Our central hub in Nishinomiya, Hyogo, providing direct support to Japanese students.',
    'home.testimonials.title': 'What Our Students Say',
    'home.cta.label': 'READY TO START?',
    'home.cta.title1': 'Your Global Journey ',
    'home.cta.title2': 'Begins Now',
    'home.cta.description': 'Take the first step towards an international future. Book your free consultation today and discover a world of possibilities.',
    'home.cta.button': 'Book Free Consultation',
    'home.cta.note': 'First 30 minutes completely free • No obligation',

    // About Page
    'about.hero.title': 'About ',
    'about.hero.desc': 'Nurturing globally confident individuals who can carve their own path on the world stage and create meaningful futures without limitations.',
    'about.info.title': 'HANAMICHI LLC',
    'about.info.address.label': 'Address',
    'about.info.phone.label': 'Phone',
    'about.info.email.label': 'Email',
    'about.info.rep.label': 'Representative',
    'about.info.business.label': 'Business',
    'about.info.business.desc': 'International career support, study abroad counselling, university admission guidance, workshop planning, and educational mentoring.',
    'about.vision.title': 'Our Vision',
    'about.vision.desc': 'To create a world where every individual has the confidence and opportunity to pursue their dreams globally, regardless of their background.',
    'about.mission.title': 'Our Mission',
    'about.mission.desc': 'To provide expert guidance and transformative international experiences that empower students to become global citizens and leaders.',
    'about.philosophy.title': 'Our Philosophy',
    'about.philosophy.desc': 'Education should not only focus on exams and admissions. It should help students discover confidence, strengths, purpose, and future possibilities. HANAMICHI supports students step-by-step throughout their educational journey through personalized international guidance.',

    // Programs Page
    'programs.hero.title': 'Our Programs',
    'programs.hero.desc': 'From study tours to university admissions, we offer comprehensive support for your international education journey.',
    'programs.counselor.title': 'School Counselor',
    'programs.counselor.desc': 'B2B college counselor dispatch to schools',
    'programs.studyTours.title': 'Study Tours',
    'programs.studyTours.desc': 'Short-term international study programs',
    'programs.university.title': 'University Admission',
    'programs.university.desc': 'Taiwan & English-speaking university support',
    'programs.highSchool.title': 'High School Abroad',
    'programs.highSchool.desc': 'Canada & New Zealand high school opportunities',
    'programs.mandarin.title': 'Mandarin Chinese',
    'programs.mandarin.desc': 'Online Mandarin learning with Taiwanese teachers',
    'programs.counselling.title': 'Counselling',
    'programs.counselling.desc': 'Career counselling online or in-person',
    'programs.workshop.title': 'Workshop',
    'programs.workshop.desc': 'Self-discovery workshops twice/year',
    'programs.mentoring.title': 'Mentoring',
    'programs.mentoring.desc': 'Long-term mentoring support',
    'programs.comingSoon': 'Coming Soon',
    'programs.learnMore': 'Learn more',

    // Why Us Page
    'whyUs.hero.title': 'Why Choose HANAMICHI',
    'whyUs.hero.desc': 'Discover what makes HANAMICHI different from other educational agencies and why students choose us for their international journey.',
    'whyUs.feature1.title': 'Step-by-step Personalized Design',
    'whyUs.feature1.desc': 'Even with the same grades, the optimal path differs. We expand possibilities at each developmental stage.',
    'whyUs.feature2.title': 'Long-term Perspective Beyond Exam Year',
    'whyUs.feature2.desc': 'We look beyond university acceptance toward career and social engagement.',
    'whyUs.feature3.title': 'Making Overseas Universities Accessible',
    'whyUs.feature3.desc': "You don't need perfect English. There are step-by-step routes worldwide.",
    'whyUs.feature4.title': 'Real Experience + Multi-faceted Expertise',
    'whyUs.feature4.desc': 'Active educational counselling with international and practical experience.',
    'whyUs.feature5.title': 'Network Spanning 20+ Countries',
    'whyUs.feature5.desc': 'Strong educational partnerships and real global connections.',

    // Partners Page
    'partners.hero.title': 'Our Partners',
    'partners.hero.desc': 'Building bridges to educational excellence through our global network of partner institutions.',
    'partners.overseas.title': 'Overseas Educational Institutions',
    'partners.domestic.label': 'Domestic Partner',
    'partners.domestic.location': 'Nishinomiya, Hyogo, Japan',
    'partners.domestic.desc': 'International career guidance partnership.',
    'partners.destinations.title': 'University Destinations',
    'partners.destinations.subtitle': '106 acceptances across 18 countries (as of April 2026)',

    // FAQ Page
    'faq.hero.title': 'Frequently Asked Questions',
    'faq.hero.desc': 'We understand that studying abroad and planning an international future can feel overwhelming. Here are answers to some of the most common questions students and parents ask HANAMICHI.',
    'faq.q1.q': 'What level of English do I need?',
    'faq.q1.a': 'It depends on the country and program you choose. Some pathways require English proficiency, while others provide step-by-step support starting from beginner level.',
    'faq.q2.q': 'From what grade can I consult?',
    'faq.q2.a': 'Students can begin consultations from junior high school. Early planning allows families to explore more opportunities.',
    'faq.q3.q': 'How much does it cost?',
    'faq.q3.a': 'Program fees vary depending on destination and duration. Examples: Taiwan universities: approximately JPY 600,000/year, Ireland short-term programs: approximately JPY 400,000+',
    'faq.q4.q': 'Is counselling online or in-person?',
    'faq.q4.a': 'Both options are available through Zoom or at the Takarazuka office.',
    'faq.q5.q': 'Can parents join the consultation?',
    'faq.q5.a': 'Yes. Parent participation is highly encouraged.',
    'faq.q6.q': 'What are the advantages of studying in Taiwan?',
    'faq.q6.a': 'Safe environment, affordable tuition, scholarship opportunities, multilingual learning, and close proximity to Japan.',
    'faq.q7.q': 'How is HANAMICHI different from other agencies?',
    'faq.q7.a': 'We focus on long-term personalized educational guidance beyond university admissions.',
    'faq.q8.q': 'Are there short-term study tours?',
    'faq.q8.a': 'Yes. Seasonal international study tours are available from 1 week.',
    'faq.q9.q': 'What payment methods are available?',
    'faq.q9.a': 'Bank transfer.',
    'faq.q10.q': 'How is personal information managed?',
    'faq.q10.a': 'All personal information is managed securely according to our Privacy Policy.',
    'faq.q11.q': 'Can students with low English ability still study abroad?',
    'faq.q11.a': 'Yes. Many pathways allow gradual language development.',
    'faq.q12.q': 'Do you help with scholarships?',
    'faq.q12.a': 'Yes. We provide scholarship guidance and affordable pathway support.',
    'faq.q13.q': 'Which countries are available for study tours?',
    'faq.q13.a': 'Taiwan, UK, Ireland, Canada, Malaysia, Finland, Czech Republic, Cambodia, Spain, and Australia.',
    'faq.q14.q': 'How long does the application process take?',
    'faq.q14.a': 'It depends on the country and institution. Early consultation is recommended.',
    'faq.q15.q': 'How can I start my journey with HANAMICHI?',
    'faq.q15.a': 'Book a free consultation session to discuss goals, programs, and future opportunities.',
    'faq.cta.title': 'Still Have Questions?',
    'faq.cta.desc': 'Our team is happy to support students and families through every step of the international education journey.',
    'faq.cta.consultation': 'Book Free Consultation',
    'faq.cta.contact': 'Contact HANAMICHI',

    // Contact Page
    'contact.hero.title': 'Contact Us',
    'contact.hero.desc': "Let's discuss your future opportunities and educational goals.",
    'contact.form.title': 'Send us a message',
    'contact.form.name': 'Name',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Phone (Optional)',
    'contact.form.message': 'Message',
    'contact.form.placeholder.name': 'Your name',
    'contact.form.placeholder.phone': 'Your phone number',
    'contact.form.placeholder.message': 'Tell us about your goals and interests...',
    'contact.form.submit': 'Send Message',
    'contact.details.title': 'Get in Touch',
    'contact.details.phone': 'Phone',
    'contact.details.email': 'Email',
    'contact.details.address': 'Address',
    'contact.details.address.value': '2-1-3 Nigawa Takamaru, Takarazuka, Hyogo, Japan',
    'contact.offer.label': 'Special Offer',
    'contact.offer.title': 'Book Your Free Consultation',
    'contact.offer.desc': 'The first 30 minutes are completely free. Let\'s explore your future together.',
    'contact.offer.free': 'First 30 minutes FREE',

    // Footer
    'footer.company.desc': 'Nurturing globally confident individuals who can carve their own path on the world stage.',
    'footer.links.title': 'Quick Links',
    'footer.programs.title': 'Programs',
    'footer.contact.title': 'Contact',
    'footer.rights': 'All rights reserved.',

    // Common
    'common.learnMore': 'Learn More',
    'common.comingSoon': 'Coming Soon',
  },
  jp: {
    // Navigation
    'nav.home': 'ホーム',
    'nav.about': '私たちについて',
    'nav.programs': 'プログラム',
    'nav.whyUs': '選ばれる理由',
    'nav.partners': 'パートナー',
    'nav.faq': 'FAQ',
    'nav.contact': 'お問い合わせ',
    'nav.freeConsultation': '無料相談',

    // Hero Section
    'hero.label': '花道グローバル教育',
    'hero.title1': '夢を叶えるための',
    'hero.title2': '最高の場所を',
    'hero.title3': '見つけよう。',
    'hero.description': 'キャリアプランニングは、あなたの未来をワクワクさせる冒険です。今日の一歩が、素晴らしいあなたに出会うまで。',
    'hero.cta1': '無料相談',
    'hero.cta2': 'プログラムを見る',
    'hero_2.label': '国際的な機会',
    'hero_2.title1': 'あなたの',
    'hero_2.title2': 'グローバルな可能性を',
    'hero_2.title3': '今、解き放つ。',
    'hero_2.description': '視野を広げ、国際的なキャリアを築くために設計された、世界クラスの大学や人生を変えるスタディツアーへのアクセス。',
    'hero_3.label': '専門家によるガイダンス',
    'hero_3.title1': '成功への',
    'hero_3.title2': 'あなたの旅は',
    'hero_3.title3': 'ここから始まる。',
    'hero_3.description': 'あらゆるレベルの学生が、未来を変える隠れた道筋や国際的な経験を発見するためのステップバイステップのガイダンス。',

    // Home Page Sections
    'home.recruiting.label': '募集中',
    'home.recruiting.title': '現在申し込み受付中のプログラム',
    'home.recruiting.viewAll': 'すべてのプログラムを見る',
    'home.invisible.label': '見えないものを見る',
    'home.invisible.title1': '一部の機会は',
    'home.invisible.title2': '誰かが示すまで',
    'home.invisible.title3': '見ることができません',
    'home.invisible.description': '私たちは、他の人が見逃しがちな道を発見するお手伝いをし、あなたの可能性に真にマッチした未来へと導きます。',
    'home.trackRecord.label': '私たちの実績',
    'home.trackRecord.title': 'グローバルな展開、ローカルな影響',
    'home.trackRecord.description': '私たちは、世界中の名門校や人生を変える経験へと学生を導くことに成功してきました。',
    'home.whyHanamichi.title': '花道が選ばれる理由',
    'home.whyHanamichi.feature1.title': '一人ひとりに合わせた道',
    'home.whyHanamichi.feature1.desc': 'あなたの独自の強みと目標に焦点を当て、最適な国際的なフィット感を見つけます。',
    'home.whyHanamichi.feature2.title': '専門的なカウンセリング',
    'home.whyHanamichi.feature2.desc': '経験豊富なメンターが、あなたのグローバルな旅をエンドツーエンドでサポートします。',
    'home.whyHanamichi.feature3.title': 'グローバルネットワーク',
    'home.whyHanamichi.feature3.desc': '世界中のトップ大学や機関との独占的なパートナーシップにアクセスできます。',
    'home.whyHanamichi.feature4.title': '実証された成功',
    'home.whyHanamichi.feature4.desc': '私たちのプログラムを通じて人生を変えた何百人もの学生の仲間に加わりましょう。',
    'home.whyHanamichi.feature5.title': 'コミュニティサポート',
    'home.whyHanamichi.feature5.desc': 'グローバル志向の人々の繁栄するネットワークの一員になりましょう。',
    'home.journey.title': '花道との歩み',
    'home.journey.step1.title': '無料相談',
    'home.journey.step1.desc': '学生の目標と興味を理解する。',
    'home.journey.step2.title': 'プログラム計画',
    'home.journey.step2.desc': '国や教育機関を選択する。',
    'home.journey.step3.title': '準備',
    'home.journey.step3.desc': '語学研修と文化オリエンテーション。',
    'home.journey.step4.title': '出願',
    'home.journey.step4.desc': '入学手続きと書類作成のサポート。',
    'home.journey.step5.title': '出発',
    'home.journey.step5.desc': '最終ブリーフィングと渡航手配。',
    'home.journey.step6.title': '現地サポート',
    'home.journey.step6.desc': '滞在中の継続的なガイダンス。',
    'home.partners.label': 'パートナー',
    'home.partners.title': 'グローバルな提携',
    'home.partners.subtitle': '海外提携機関',
    'home.partners.viewAll': 'すべてのパートナーを見る',
    'home.partners.domestic.label': '国内拠点',
    'home.partners.domestic.title': '合同会社花道 — 日本オフィス',
    'home.partners.domestic.desc': '兵庫県西宮市にある当社の中心拠点で、日本の学生に直接サポートを提供しています。',
    'home.testimonials.title': '学生の声',
    'home.cta.label': '準備はできましたか？',
    'home.cta.title1': 'あなたのグローバルな旅は ',
    'home.cta.title2': '今始まる',
    'home.cta.description': '国際的な未来への第一歩を踏み出しましょう。今すぐ無料相談を予約して、可能性の世界を発見してください。',
    'home.cta.button': '無料相談を予約する',
    'home.cta.note': '最初の30分は完全無料 • 無理な勧誘はありません',

    // About Page
    'about.hero.title': '私たちについて',
    'about.hero.desc': '世界舞台で自らの道を切り拓き、制限のない有意義な未来を創造できる、グローバルに自信のある個人を育成します。',
    'about.info.title': '合同会社花道',
    'about.info.address.label': '住所',
    'about.info.phone.label': '電話番号',
    'about.info.email.label': 'メールアドレス',
    'about.info.rep.label': '代表者',
    'about.info.business.label': '事業内容',
    'about.info.business.desc': '国際キャリア支援、留学カウンセリング、大学入学指導、ワークショップ企画、教育メンタリング。',
    'about.vision.title': '私たちのビジョン',
    'about.vision.desc': 'バックグラウンドに関わらず、すべての個人がグローバルに夢を追求できる自信と機会を持つ世界を創造すること。',
    'about.mission.title': '私たちのミッション',
    'about.mission.desc': '学生がグローバルな市民およびリーダーになれるよう、専門的なガイダンスと変革をもたらす国際的な経験を提供すること。',
    'about.philosophy.title': '私たちの理念',
    'about.philosophy.desc': '教育は試験や入学だけに焦点を当てるべきではありません。学生が自信、強み、目的、そして未来の可能性を発見するのを助けるべきです。花道は、一人ひとりに合わせた国際的なガイダンスを通じて、学生の教育の旅を段階的にサポートします。',

    // Programs Page
    'programs.hero.title': 'プログラム',
    'programs.hero.desc': 'スタディツアーから大学進学まで、国際教育の旅をトータルにサポートします。',
    'programs.counselor.title': 'スクールカウンセラー',
    'programs.counselor.desc': '学校へのB2B大学カウンセラー派遣',
    'programs.studyTours.title': 'スタディツアー',
    'programs.studyTours.desc': '短期海外研修プログラム',
    'programs.university.title': '大学進学',
    'programs.university.desc': '台湾・英語圏の大学進学サポート',
    'programs.highSchool.title': '高校留学',
    'programs.highSchool.desc': 'カナダ・ニュージーランドの高校留学',
    'programs.mandarin.title': '中国語（マンダリン）',
    'programs.mandarin.desc': '台湾人講師によるオンライン中国語学習',
    'programs.counselling.title': 'カウンセリング',
    'programs.counselling.desc': 'オンラインまたは対面でのキャリアカウンセリング',
    'programs.workshop.title': 'ワークショップ',
    'programs.workshop.desc': '年2回の自己発見ワークショップ',
    'programs.mentoring.title': 'メンタリング',
    'programs.mentoring.desc': '長期的なメンタリングサポート',
    'programs.comingSoon': '近日公開',
    'programs.learnMore': '詳しく見る',

    // Why Us Page
    'whyUs.hero.title': '花道が選ばれる理由',
    'whyUs.hero.desc': '他の教育エージェンシーとは何が違うのか、なぜ多くの学生が私たちの国際的な旅を選ぶのかをご覧ください。',
    'whyUs.feature1.title': 'ステップバイステップの一人ひとりに合わせたデザイン',
    'whyUs.feature1.desc': '同じ成績であっても、最適な道は異なります。私たちは各発達段階で可能性を広げます。',
    'whyUs.feature2.title': '受験学年を超えた長期的な視点',
    'whyUs.feature2.desc': '大学合格の先にあるキャリアや社会参画を見据えています。',
    'whyUs.feature3.title': '海外大学を身近に',
    'whyUs.feature3.desc': '完璧な英語は必要ありません。世界中にステップバイステップのルートがあります。',
    'whyUs.feature4.title': 'リアルな経験 ＋ 多角的な専門知識',
    'whyUs.feature4.desc': '国際的かつ実践的な経験を持つ、現役の教育カウンセリング。',
    'whyUs.feature5.title': '20カ国以上にわたるネットワーク',
    'whyUs.feature5.desc': '強力な教育パートナーシップと本物のグローバルなつながり。',

    // Partners Page
    'partners.hero.title': 'パートナー',
    'partners.hero.desc': 'グローバルな提携機関ネットワークを通じて、優れた教育への架け橋を築きます。',
    'partners.overseas.title': '海外提携教育機関',
    'partners.domestic.label': '国内パートナー',
    'partners.domestic.location': '兵庫県西宮市、日本',
    'partners.domestic.desc': '国際キャリアガイダンス提携',
    'partners.destinations.title': '進学先大学',
    'partners.destinations.subtitle': '18カ国106件の合格実績（2026年4月現在）',

    // FAQ Page
    'faq.hero.title': 'よくある質問',
    'faq.hero.desc': '留学や国際的な未来の計画は、時に圧倒されることもあるでしょう。花道に寄せられる、学生や保護者の方々からの代表的な質問にお答えします。',
    'faq.q1.q': 'どの程度の英語力が必要ですか？',
    'faq.q1.a': '国や選択するプログラムによって異なります。英語力が必要なルートもあれば、初心者レベルから段階的にサポートするルートもあります。',
    'faq.q2.q': '何年生から相談できますか？',
    'faq.q2.a': '中学生からご相談いただけます。早い段階からの計画により、より多くの機会を検討することが可能になります。',
    'faq.q3.q': '費用はどのくらいかかりますか？',
    'faq.q3.a': '目的地や期間によって異なります。例：台湾の大学：年間約60万円〜、アイルランド短期研修：約40万円〜。',
    'faq.q4.q': 'カウンセリングはオンラインですか、対面ですか？',
    'faq.q4.a': 'Zoomによるオンライン、または宝塚オフィスでの対面、どちらも可能です。',
    'faq.q5.q': '保護者も相談に同席できますか？',
    'faq.q5.a': 'はい、保護者の方のご参加を強く推奨しています。',
    'faq.q6.q': '台湾留学のメリットは何ですか？',
    'faq.q6.a': '治安の良さ、リーズナブルな学費、奨学金制度、多言語学習環境、そして日本からの近さなどが挙げられます。',
    'faq.q7.q': '花道は他のエージェントと何が違うのですか？',
    'faq.q7.a': '大学合格だけを目的とせず、その先のキャリアを見据えた長期的な個別教育ガイダンスに重点を置いています。',
    'faq.q8.q': '短期のスタディツアーはありますか？',
    'faq.q8.a': 'はい、1週間から参加可能な季節ごとの国際スタディツアーをご用意しています。',
    'faq.q9.q': '支払方法は何がありますか？',
    'faq.q9.a': '銀行振込にて承っております。',
    'faq.q10.q': '個人情報はどのように管理されていますか？',
    'faq.q10.a': 'プライバシーポリシーに基づき、すべての個人情報は厳重かつ安全に管理されています。',
    'faq.q11.q': '英語力が低くても留学できますか？',
    'faq.q11.a': 'はい、可能です。多くのルートで段階的な語学向上をサポートしています。',
    'faq.q12.q': '奨学金のサポートはありますか？',
    'faq.q12.a': 'はい、奨学金に関する情報提供や、費用を抑えた進学ルートの提案を行っています。',
    'faq.q13.q': 'スタディツアーで行ける国はどこですか？',
    'faq.q13.a': '台湾、イギリス、アイルランド、カナダ、マレーシア、フィンランド、チェコ、カンボジア、スペイン、オーストラリアなどがあります。',
    'faq.q14.q': '手続きにはどのくらいの期間がかかりますか？',
    'faq.q14.a': '国や機関によりますが、余裕を持って1年前からのご相談をお勧めしています。',
    'faq.q15.q': 'どうすれば相談を始められますか？',
    'faq.q15.a': 'まずは無料相談をご予約ください。目標や興味に合わせたプログラムをご提案します。',
    'faq.cta.title': 'まだご質問がありますか？',
    'faq.cta.desc': '私たちのチームは、国際教育の旅のあらゆる段階で、学生とご家族を喜んでサポートします。',
    'faq.cta.consultation': '無料相談を予約する',
    'faq.cta.contact': '花道にお問い合わせ',

    // Contact Page
    'contact.hero.title': 'お問い合わせ',
    'contact.hero.desc': 'あなたの将来の機会や教育目標について話し合いましょう。',
    'contact.form.title': 'メッセージを送る',
    'contact.form.name': '氏名',
    'contact.form.email': 'メールアドレス',
    'contact.form.phone': '電話番号（任意）',
    'contact.form.message': 'メッセージ',
    'contact.form.placeholder.name': 'お名前',
    'contact.form.placeholder.phone': '電話番号',
    'contact.form.placeholder.message': 'あなたの目標や興味について教えてください...',
    'contact.form.submit': '送信',
    'contact.details.title': '連絡先',
    'contact.details.phone': '電話',
    'contact.details.email': 'メール',
    'contact.details.address': '住所',
    'contact.details.address.value': '兵庫県宝塚市仁川高丸2-1-3',
    'contact.offer.label': '特別オファー',
    'contact.offer.title': '無料相談を予約する',
    'contact.offer.desc': '最初の30分は完全無料です。一緒にあなたの未来を模索しましょう。',
    'contact.offer.free': '初回30分無料',

    // Footer
    'footer.company.desc': '世界舞台で自らの道を切り拓くことができる、グローバルに自信のある個人を育成します。',
    'footer.links.title': 'クイックリンク',
    'footer.programs.title': 'プログラム',
    'footer.contact.title': 'お問い合わせ',
    'footer.rights': 'All rights reserved.',

    // Common
    'common.learnMore': '詳しく見る',
    'common.comingSoon': '近日公開',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
